# Generated by Django 5.1.1 on 2024-09-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('birth_date', models.DateField()),
                ('password', models.CharField(max_length=20)),
                ('conmirf_password', models.CharField(max_length=20)),
            ],
        ),
    ]
