# Generated by Django 5.1.1 on 2024-09-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_conmirf_password_registration_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='confirm_password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
