# Generated by Django 5.1.1 on 2024-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_registration_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Student', 'Student')], default='Student', max_length=100),
        ),
    ]
