# Generated by Django 5.1.1 on 2024-09-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DivisionName', models.CharField(max_length=10)),
                ('seat', models.IntegerField()),
                ('Standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.standard')),
            ],
        ),
    ]
