# Generated by Django 5.1.1 on 2024-09-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='Standard',
            new_name='standard',
        ),
    ]
