# Generated by Django 5.1.1 on 2024-09-29 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_standard_division_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30)),
                ('Qualification', models.CharField(max_length=15)),
                ('forkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registration')),
            ],
        ),
    ]
